[project]
name = "complexityscanner"
version = "1.1.1"
description = "Cyclomatic complexity scanner and report generator"
authors = [
  { name = "Thomas Lindqvist", email = "fixaren54_eon@icloud.com" }
]
license = "MIT"
dependencies = [
  "jinja2",
  "pytest",
  "coverage",
  "pydriller"
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"